destination: _site/book
exclude:
  - "*.yml"
imageWidth: 95%
imageHeight: auto
coverImage: '<meta content="cover_image" name="cover" />'
responsibilityModelImage:
devExImage:
responsibilityTriadImage:
devopsImage:
deeasImage:
idpImage:
tocParent: ol
tocChild: li